### ISSUE TITLE
CS model code

### ISSUE THREAD

**Issue by jules32** [OHI-Science/bali#1]
Question from @rftapilatu: 

I have read all references for OHI toolbox and played with R, R-Studio to analyze data.  I understood how git and github functions and played with it to make ggplot for CS data.  Now I'm in the process to analyze CS data from Bali.  Could you guide me where to find available R-script (whether in OHI global or somewhere) so then I can get it to start analyzing the data.

**Comment by jules32** [comment]
Hi @rftapilatu,

The CS model is in [conf/functions.r](https://github.com/OHI-Science/bali/blob/master/region2017/conf/functions.R#L726-L813). 

You'll be able to modify this as you need to, depending on whether this is the same model you'd like to use, and depending on the data you're including. 

To run it, you'll need to have first run [`install_ohicore.r`](https://github.com/OHI-Science/bali/blob/master/install_ohicore.R) and then run the first lines in [`calculate_scores.r`](https://github.com/OHI-Science/bali/blob/master/region2017/calculate_scores.R#L8-L11). Then, you can work within the CS function in `functions.r`. 

If you haven't done so yet, read the toolbox-training chapter on [basic calculations workflow](http://ohi-science.org/toolbox-training/calcs-basic.html), and follow along with the bali repository. It will show you the steps you'll need to do when you have your data prepared and saved in the /layers folder and registered in layers.csv.

Let me know if you have further questions and we can set up a Skype call.
- Julie

**Comment by rftapilatu** [comment]
No wonder via wiki I did not get a response.
Thanks Julia for creating an issue for us to communicate and we get a notification in our e-mail as well to check it out at github, cool. 
Great response, I will check the instruction and if I have question, will talk with you over skype.

**Comment by rftapilatu** [comment]
Hi Julia and Bali Team,
Please have a look at Bali Folder on what we got here with CS score. Let me know whether I have gone through the correct procedure or not.

**Comment by rftapilatu** [comment]
The file name is scores_CSBaliRFT
